### ISSUE TITLE
Parking brake appears to do nothing with wheels retracted

### ISSUE THREAD

**Issue by PrimeJunta** [jarosm/KSP-ParkingBrake#1]
To reproduce:
1. Fly the attached craft from the SPH.
2. Drive it near the bottom of the incline next to the runway.
3. Engage brake action group and retract the wheels (gear action group).
4. Wait for drift to fall below 0.1 m/s.
5. Engage Parking Brake.
* Expected: craft movement stops
* Observed: it continues to drift

Note: with the wheels extended, Parking Brake stops the craft's drift dead as expected.

[WHEELED ISRU.zip](https://github.com/jarosm/KSP-ParkingBrake/files/2617060/WHEELED.ISRU.zip)

**Comment by jarosm** [comment]
Speed limit increased to 0.25 m/s

**Comment by PrimeJunta** [comment]
The drift is still present. I made some adjustments to the test craft which should make it easier to reproduce. It drifts more easily at a very slow speed now.

Test 1: wheels deployed

1. Fly the attached craft from the SPH.
2. Drive it near the bottom of the incline next to the runway.
3. Engage brakes
4. Wait for speed to drop below 0.1 m/s
* Observed: Craft is drifting
5. Engage Parking Brake
* Observed: Craft appears to stop
6. Zoom in close to the wheel to observe the wheel/ground interaction
* Observed: craft is drifting downhill very very slowly

Test 2: wheels retracted
1. Follow steps 1-3 above
2. Retract wheels
3. Follow steps 4-7 above
* Observed: drift, slightly faster than above

Test 3: no wheels
1. Follow steps 1-3 above
2. Deploy stages to eject wheels
3. Follow steps 4-7 above
* Observed: very slow drift, as when wheels are deployed

There really seems to be something devilishly complicated about this -- I looked at your code and it's simple, logical, and makes sense!

[WHEELED ISRU.zip](https://github.com/jarosm/KSP-ParkingBrake/files/2617373/WHEELED.ISRU.zip)

**Comment by jarosm** [comment]
The problem are wheels, because they very slowly rotate. Your rover is heavy and they don't have that much braking force. When you retract them, then your ISRU isn't landed, so parking brake is disabled automatically.

I tried to mount pair of landing lags and it improved it dramatically, but even if parking brake stops that big sliding, there is still a little bit of sliding on steeper hill. This definitelly needs some investigation.
